name: Auto sync forked repo
description: Automatically synchronize the original repo with the forked repo.

branding:
  icon: git-merge
  color: yellow

# inputs:
  # 입력값
    
# outputs:
  # 출력값
    
runs:
  using: "composite"
  steps:
    - name: "Echo"
      run: echo "It works!"
