name: Auto sync forked repo
description: Automatically synchronize the original repo with the forked repo.

branding:
  icon: git-merge
  color: yellow

inputs:
  upstream_repository_owner:
    description: 'Owner of the upstream repository'
    required: true
  upstream_repository_name:
    description: 'Name of the upstream repository'
    required: true
  forked_repository_owner:
    description: 'Owner of the forked repository'
    required: true
  forked_repository_name:
    description: 'Name of the forked repository'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Print Repository Information"
      shell: bash
      run: |
        echo "Upstream Repository: ${{ inputs.upstream_repository_owner }}/${{ inputs.upstream_repository_name }}"
        echo "Forked Repository: ${{ inputs.forked_repository_owner }}/${{ inputs.forked_repository_name }}"
