name: Auto sync forked repo
description: Automatically synchronize the original repo with the forked repo.

branding:
  icon: git-merge
  color: yellow

inputs:
  upstream_repository_owner:
    description: 'Owner of the upstream repository'
    required: true
  upstream_repository_name:
    description: 'Name of the upstream repository'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Fetch Upstream"
      shell: bash
      run: |
          git remote add upstream https://github.com/${{ inputs.upstream_repository_owner }}/${{ inputs.upstream_repository_name  }}.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
